import { execa } from "execa";
import fs from "node:fs/promises";
import path from "node:path";

import type { pm, WebflowJSON } from "./types.js";

/**
 * Sanitizes a project name string to be URL- and filesystem-friendly.
 *
 * The function performs the following transformations:
 * - Converts the string to lowercase.
 * - Trims leading and trailing whitespace.
 * - Replaces spaces with hyphens.
 * - Removes all characters except lowercase letters, numbers, and hyphens.
 * - Collapses multiple consecutive hyphens into a single hyphen.
 * - Removes leading and trailing hyphens.
 * - Truncates the result to a maximum of 214 characters.
 *
 * If the sanitized result is empty, returns "my-webflow-extension".
 *
 * @param name - The original project name to sanitize.
 * @returns The sanitized project name.
 */

export function sanitizeProjectName(name: string): string {
  const sanitized = name
    .toLowerCase()
    .trim()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 214);

  if (!sanitized) {
    return "my-webflow-extension";
  }

  return sanitized;
}

/**
 * Checks asynchronously whether a given directory exists.
 *
 * @param dir - The path to the directory to check.
 * @returns A promise that resolves to `true` if the directory exists, or `false` otherwise.
 */

export async function directoryExists(dir: string): Promise<boolean> {
  try {
    const stat = await fs.stat(dir);
    return stat.isDirectory();
  } catch {
    return false;
  }
}

/**
 * Updates the `package.json` file in the specified target directory.
 *
 * - Sets the project name.
 * - Replaces the default package manager (`pnpm`) in scripts with the user's chosen package manager (`pnpm`, `npm`, or `yarn`).
 * - Attempts to set the `author` and `contributors` fields using the local git configuration (`user.name` and `user.email`), if available.
 *
 * @param targetDir - The directory containing the `package.json` to update.
 * @param projectName - The new name to set for the project.
 * @param pm - The package manager to use in scripts (`pnpm`, `npm`, or `yarn`).
 * @returns A promise that resolves when the update is complete.
 */

export async function updatePackageJSON(
  targetDir: string,
  projectName: string,
  pm: pm
): Promise<void> {
  const pkgPath = path.join(targetDir, "package.json");
  const content = await fs.readFile(pkgPath, "utf-8");
  const pkg = JSON.parse(content);

  pkg.name = projectName;
  pkg.version = "0.1.0";
  pkg.description = `${projectName} Webflow Designer Extension`;

  // Replace Default PM with User's PM in Scripts
  if (pm !== "pnpm" && pkg.scripts) {
    for (const [key, value] of Object.entries(pkg.scripts)) {
      if (typeof value === "string") {
        pkg.scripts[key] = value.replace(/\bpnpm\b/g, pm);
      }
    }
  }

  // Use git Config (If Available) to Set Author and Contributor
  try {
    const { stdout } = await execa("git", [
      "config",
      "--get-regexp",
      "^user\\.(name|email)$",
    ]);

    const gitConfig: Record<string, string> = {};
    for (const line of stdout.split("\n")) {
      const match = line.match(/^user\.(\w+)\s+(.+)$/);
      if (match) {
        gitConfig[match[1]] = match[2];
      }
    }

    if (gitConfig.name) {
      const person = {
        name: gitConfig.name,
        ...(gitConfig.email && { email: gitConfig.email }),
      };
      pkg.author = person;
      pkg.contributors = [person];
    }
  } catch {}

  await fs.writeFile(pkgPath, JSON.stringify(pkg, null, "\t") + "\n");
}

/**
 * Updates the `webflow.json` file in the specified target directory by setting the `name` property
 * to a formatted display name based on the provided project name.
 *
 * The display name is generated by splitting the `projectName` on hyphens, capitalizing the first
 * letter of each word, and joining them with spaces.
 *
 * @param targetDir - The directory containing the `webflow.json` file to update.
 * @param projectName - The project name used to generate the display name for the `name` property.
 * @returns A promise that resolves when the file has been updated.
 * @throws Will throw an error if reading or writing the file fails, or if the JSON is invalid.
 */

export async function updateWebflowJSON(
  targetDir: string,
  projectName: string
): Promise<void> {
  const webflowPath = path.join(targetDir, "webflow.json");
  const content = await fs.readFile(webflowPath, "utf-8");
  const config: WebflowJSON = JSON.parse(content);

  const displayName = projectName
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");

  config.name = displayName;

  await fs.writeFile(webflowPath, JSON.stringify(config, null, "\t") + "\n");
}
